#JRELEASER_GITHUB_TOKEN = "**INVALID**"
JRELEASER_GITLAB_TOKEN = "**INVALID**"
JRELEASER_GITEA_TOKEN = "**INVALID**"
JRELEASER_CODEBERG_TOKEN = "**INVALID**"
JRELEASER_DISCORD_WEBHOOK = "**INVALID**"
JRELEASER_DISCOURSE_USERNAME = "**INVALID**"
JRELEASER_DISCOURSE_API_KEY = "**INVALID**"
JRELEASER_DISCOURSE_CATEGORY_NAME = "**INVALID**"
JRELEASER_GITTER_WEBHOOK = "**INVALID**"
JRELEASER_GOOGLE_CHAT_WEBHOOK = "**INVALID**"
JRELEASER_LINKEDIN_ACCESS_TOKEN = "**INVALID**"
JRELEASER_HTTP_NEWS_USERNAME = "**INVALID**"
JRELEASER_HTTP_NEWS_PASSWORD = "**INVALID**"
JRELEASER_MAIL_PASSWORD = "**INVALID**"
JRELEASER_MASTODON_ACCESS_TOKEN = "**INVALID**"
JRELEASER_MATTERMOST_WEBHOOK = "**INVALID**"
JRELEASER_SLACK_WEBHOOK = "**INVALID**"
JRELEASER_TEAMS_WEBHOOK = "**INVALID**"
JRELEASER_TELEGRAM_TOKEN = "**INVALID**"
JRELEASER_TELEGRAM_CHAT_ID = "**INVALID**"
JRELEASER_TWITTER_CONSUMER_KEY = "**INVALID**"
JRELEASER_TWITTER_CONSUMER_SECRET = "**INVALID**"
JRELEASER_TWITTER_ACCESS_TOKEN = "**INVALID**"
JRELEASER_TWITTER_ACCESS_TOKEN_SECRET = "**INVALID**"
JRELEASER_ACME_WEBHOOK = "**INVALID**"
JRELEASER_ZULIP_API_KEY = "**INVALID**"
JRELEASER_ARTIFACTORY_TOKEN = "**INVALID**"
JRELEASER_NEXUS2_USERNAME = "**INVALID**"
JRELEASER_NEXUS2_TOKEN = "**INVALID**"
JRELEASER_FTP_D2_HOST = "**INVALID**"
JRELEASER_SSH_USERNAME = "**INVALID**"
JRELEASER_SSH_PASSWORD = "**INVALID**"
JRELEASER_SSH_HOST = "**INVALID**"
JRELEASER_FTP_U2_HOST = "**INVALID**"
JRELEASER_FTP_U2_USERNAME = "**INVALID**"
JRELEASER_FTP_U2_PASSWORD = "**INVALID**"
JRELEASER_ARTIFACTORY_U1_PASSWORD = "**INVALID**"
JRELEASER_S3_U6_REGION = "**INVALID**"
JRELEASER_S3_U6_BUCKET = "**INVALID**"
JRELEASER_SSH_PORT = "22"
JRELEASER_SDKMAN_CONSUMER_KEY = "**INVALID**"
JRELEASER_SDKMAN_CONSUMER_TOKEN = "**INVALID**"
JRELEASER_DOCKER_DEFAULT_PASSWORD = "**INVALID**"

